### ISSUE TITLE
Failing to Update A/B Activities

### ISSUE THREAD

**Issue by seanblonien** [adobe/aio-lib-target#54]
### Expected Behaviour
Target SDK _or_ Target API allow you to update Target A/B activities, including ones that have auto-allocate.

### Actual Behaviour
Unable to update Target A/B activities with SDK or API.

#### Using this SDK
```
// Get and update single activity
const response = await targetClient.getABActivityById(395705);
const body = response.body;
await targetClient.updateABActivity(395705, body);
```
throws this error
<details>
<summary>error</summary>

```
[TargetSDK:ERROR_UPDATE_AB_ACTIVITY] Error: Conflict
    at _callee$ (C:\Git\TargetAPI\node_modules\swagger-client\dist\index.js:623:816)
    at tryCatch (C:\Git\TargetAPI\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Git\TargetAPI\node_modules\regenerator-runtime\runtime.js:293:22)
    at Generator.next (C:\Git\TargetAPI\node_modules\regenerator-runtime\runtime.js:118:21)
    at asyncGeneratorStep (C:\Git\TargetAPI\node_modules\@babel\runtime-corejs2\helpers\asyncToGenerator.js:5:24)
    at _next (C:\Git\TargetAPI\node_modules\@babel\runtime-corejs2\helpers\asyncToGenerator.js:27:9)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  status: 409,
  statusCode: 409,
  response: [Object]
}
```

</details>

#### Using HTTP API
In Postman, with this request  `https://mc.adobe.io/{{tenant}}/target/activities/ab/395705` that was given to me by your Postman collection from the documentation (no modifications made besides filling in variables), with body being the exact response from the corresponding Get request for ab activity, gives this error

<details>
<summary>error</summary>

```
{
    "httpStatus": 409,
    "requestId": "YqYAZftfoxjPU3F1ZKJHsGyPuzK2NAJo",
    "requestTime": "2021-04-16T19:47:29.076182Z",
    "errors": [
        {
            "errorCode": "VersionConflict.Resource",
            "message": "Cannot create/update auto-allocate activity with this version of API"
        }
    ]
}
```

</details>

#### Platform and Version

SDK
"@adobe/aio-lib-target": "^2.1.1"

API
application/vnd.adobe.target.v3+json

Node.js
v14.15.4

#### Sample Code that illustrates the problem

Here's the whole Node.js file reproducing it:

<details>
<summary>code</summary>

```
const sdk = require('@adobe/aio-lib-target');

(async () => {
    const client = await sdk.init('tenant', 'key', 'token');

    try {
      // Get single and update activity
      const response = await client.getABActivityById(395705);
      const body = response.body;
      await client.updateABActivity(395705, body);
    } catch(e) {
      console.log(e.message);
    }
})();
```

</details>

**Comment by meryllblanchet** [comment]
Hi @seanblonien ,

Thanks for opening the issue.
We are maintaining Project Firefly SDK, and this library is part of the framework. However we are not maintaining the Target API itself, which is handled by the Adobe Target team.

I see that the Target SDK behavior is aligned with the Target API response, and this is what to expect.
Please reach out to the Adobe Target team, and we'll be glad to update the library according to any relevant update from the API.

On a side note, we do not support NodeJS 14 yet for the SDK as per [our Project Firefly documentation](https://www.adobe.io/apis/experienceplatform/project-firefly/docs.html#!AdobeDocs/project-firefly/master/getting_started/setup.md)

**Comment by sandeep-paliwal** [comment]
@seanblonien I checked the sdk call and API, looks like update AB activity works correctly with certain version of Target content type. By default the content type is 'application/vnd.adobe.target.v3+json' for which API errors out. I was able to successfully use the update call with following version ' application/vnd.adobe.target.v1+json'. 
Here is sample code on how to override default and provide your own accept headers for GET calls and Content-Type header for update calls.

```
res = await sdkClient.getABActivityById(id, {headers: {'accept': 'application/vnd.adobe.target.v1+json'}})
res = await sdkClient.updateABActivity (id, res.body, {headers : {'Content-Type' : 'application/vnd.adobe.target.v1+json'}})
```
Adobe Target Team can give more clarity on with what version update call works and why it fails in your case.

**Comment by seanblonien** [comment]
@meryllblanchet I figured y'all probably didn't support the Target API, but I wasn't sure where else to bring up this issue. I definitely will reach out to them.

What is the best way to contact the Adobe Target Team about an issue like this?

On another side note, is there a reason why you don't support NodeJS 14 yet, _especially_ knowing NodeJS 16 is being released as the current, stable, NodeJS version [this month](https://github.com/nodejs/Release)?

**Comment by meryllblanchet** [comment]
@seanblonien I would recommend you to try to get in touch with the Adobe Target team via your enterprise support as I am not aware of any direct way to do so.
Please keep us posted on this issue in case we should help you further by adapting the SDK to potential API updates.

As per your question related to NodeJS support: enabling a new version also requires all subsequent dependencies to be stable on this new version. We are currently working on enabling the NodeJS 14 support for `aio CLI` and all plugins and SDK libraries that are dependencies (ETA end of quarter).
For libraries that are more useful at runtime, like this Adobe Target one, we will sync up with I/O Runtime NodeJS 14 support, which is also work in progress.
